// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tlstatDataEvent struct {
	_         structs.HostLayout
	Type      uint8
	Direction uint8
	Len       uint16
	Pid       uint32
	Tid       uint32
	Fd        int32
	Ssl       uint64
	Data      [1024]uint8
}

type tlstatFlow struct {
	_         structs.HostLayout
	Tx        uint64
	Rx        uint64
	Pid       uint32
	Saddr     [4]uint32
	Daddr     [4]uint32
	Sport     uint16
	Dport     uint16
	IsIpv6    uint8
	Direction uint8
	IsTls     uint8
	Closed    uint8
	WireOut   uint8
	WireIn    uint8
	Comm      [16]int8
}

type tlstatRecvCtx struct {
	_    structs.HostLayout
	Sk   uint64
	Base uint64
}

type tlstatSslCtx struct {
	_   structs.HostLayout
	Ssl uint64
	Buf uint64
}

type tlstatSslStat struct {
	_       structs.HostLayout
	Ptx     uint64
	Prx     uint64
	Pid     uint32
	Fd      int32
	OutEmit uint16
	InEmit  uint16
}

type tlstatWireEvent struct {
	_         structs.HostLayout
	Type      uint8
	Direction uint8
	Len       uint16
	Sk        uint64
	Data      [1024]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tlstatMapEvents              = "events"
	tlstatMapFlows               = "flows"
	tlstatMapRecvCtxs            = "recv_ctxs"
	tlstatMapSslCtxs             = "ssl_ctxs"
	tlstatMapSslFds              = "ssl_fds"
	tlstatMapSslStats            = "ssl_stats"
	tlstatProgK_tcpRecvmsg       = "k_tcp_recvmsg"
	tlstatProgK_tcpSendmsg       = "k_tcp_sendmsg"
	tlstatProgKrTcpRecvmsg       = "kr_tcp_recvmsg"
	tlstatProgTpInetSockSetState = "tp_inet_sock_set_state"
	tlstatProgU_sslRead          = "u_ssl_read"
	tlstatProgU_sslSetFd         = "u_ssl_set_fd"
	tlstatProgU_sslWrite         = "u_ssl_write"
	tlstatProgUrSslRead          = "ur_ssl_read"
	tlstatVarUnusedDataEvent     = "_unused_data_event"
	tlstatVarUnusedFlow          = "_unused_flow"
	tlstatVarUnusedSslStat       = "_unused_ssl_stat"
	tlstatVarUnusedWireEvent     = "_unused_wire_event"
)

// loadTlstat returns the embedded CollectionSpec for tlstat.
func loadTlstat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TlstatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tlstat: %w", err)
	}

	return spec, err
}

// loadTlstatObjects loads tlstat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tlstatObjects
//	*tlstatPrograms
//	*tlstatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTlstatObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTlstat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tlstatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlstatSpecs struct {
	tlstatProgramSpecs
	tlstatMapSpecs
	tlstatVariableSpecs
}

// tlstatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlstatProgramSpecs struct {
	K_tcpRecvmsg       *ebpf.ProgramSpec `ebpf:"k_tcp_recvmsg"`
	K_tcpSendmsg       *ebpf.ProgramSpec `ebpf:"k_tcp_sendmsg"`
	KrTcpRecvmsg       *ebpf.ProgramSpec `ebpf:"kr_tcp_recvmsg"`
	TpInetSockSetState *ebpf.ProgramSpec `ebpf:"tp_inet_sock_set_state"`
	U_sslRead          *ebpf.ProgramSpec `ebpf:"u_ssl_read"`
	U_sslSetFd         *ebpf.ProgramSpec `ebpf:"u_ssl_set_fd"`
	U_sslWrite         *ebpf.ProgramSpec `ebpf:"u_ssl_write"`
	UrSslRead          *ebpf.ProgramSpec `ebpf:"ur_ssl_read"`
}

// tlstatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlstatMapSpecs struct {
	Events   *ebpf.MapSpec `ebpf:"events"`
	Flows    *ebpf.MapSpec `ebpf:"flows"`
	RecvCtxs *ebpf.MapSpec `ebpf:"recv_ctxs"`
	SslCtxs  *ebpf.MapSpec `ebpf:"ssl_ctxs"`
	SslFds   *ebpf.MapSpec `ebpf:"ssl_fds"`
	SslStats *ebpf.MapSpec `ebpf:"ssl_stats"`
}

// tlstatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tlstatVariableSpecs struct {
	UnusedDataEvent *ebpf.VariableSpec `ebpf:"_unused_data_event"`
	UnusedFlow      *ebpf.VariableSpec `ebpf:"_unused_flow"`
	UnusedSslStat   *ebpf.VariableSpec `ebpf:"_unused_ssl_stat"`
	UnusedWireEvent *ebpf.VariableSpec `ebpf:"_unused_wire_event"`
}

// tlstatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTlstatObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlstatObjects struct {
	tlstatPrograms
	tlstatMaps
	tlstatVariables
}

func (o *tlstatObjects) Close() error {
	return _TlstatClose(
		&o.tlstatPrograms,
		&o.tlstatMaps,
	)
}

// tlstatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTlstatObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlstatMaps struct {
	Events   *ebpf.Map `ebpf:"events"`
	Flows    *ebpf.Map `ebpf:"flows"`
	RecvCtxs *ebpf.Map `ebpf:"recv_ctxs"`
	SslCtxs  *ebpf.Map `ebpf:"ssl_ctxs"`
	SslFds   *ebpf.Map `ebpf:"ssl_fds"`
	SslStats *ebpf.Map `ebpf:"ssl_stats"`
}

func (m *tlstatMaps) Close() error {
	return _TlstatClose(
		m.Events,
		m.Flows,
		m.RecvCtxs,
		m.SslCtxs,
		m.SslFds,
		m.SslStats,
	)
}

// tlstatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTlstatObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlstatVariables struct {
	UnusedDataEvent *ebpf.Variable `ebpf:"_unused_data_event"`
	UnusedFlow      *ebpf.Variable `ebpf:"_unused_flow"`
	UnusedSslStat   *ebpf.Variable `ebpf:"_unused_ssl_stat"`
	UnusedWireEvent *ebpf.Variable `ebpf:"_unused_wire_event"`
}

// tlstatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTlstatObjects or ebpf.CollectionSpec.LoadAndAssign.
type tlstatPrograms struct {
	K_tcpRecvmsg       *ebpf.Program `ebpf:"k_tcp_recvmsg"`
	K_tcpSendmsg       *ebpf.Program `ebpf:"k_tcp_sendmsg"`
	KrTcpRecvmsg       *ebpf.Program `ebpf:"kr_tcp_recvmsg"`
	TpInetSockSetState *ebpf.Program `ebpf:"tp_inet_sock_set_state"`
	U_sslRead          *ebpf.Program `ebpf:"u_ssl_read"`
	U_sslSetFd         *ebpf.Program `ebpf:"u_ssl_set_fd"`
	U_sslWrite         *ebpf.Program `ebpf:"u_ssl_write"`
	UrSslRead          *ebpf.Program `ebpf:"ur_ssl_read"`
}

func (p *tlstatPrograms) Close() error {
	return _TlstatClose(
		p.K_tcpRecvmsg,
		p.K_tcpSendmsg,
		p.KrTcpRecvmsg,
		p.TpInetSockSetState,
		p.U_sslRead,
		p.U_sslSetFd,
		p.U_sslWrite,
		p.UrSslRead,
	)
}

func _TlstatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tlstat_x86_bpfel.o
var _TlstatBytes []byte
